Pull from aws ecr

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -20,6 +20,8 @@ jobs:
 
       - name: Login to Amazon ECR
         uses: aws-actions/amazon-ecr-login@v1
+        with:
+          mask-password: true
         id: login-to-ecr
 
       - name: Pull Docker image from ECR
@@ -28,7 +30,8 @@ jobs:
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
           IMAGE_TAG: latest
         run: |
-          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || echo "Image not found, will build a new one."
+          echo "${ECR_REGISTRY}"
+          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || echo "Image not found"
       
       - name: Run Playwright tests
         env:
